### ISSUE TITLE
More than 10 links induce "Cannot read property 'leaf' of undefined (angular-openlayers.js:360)"

### ISSUE THREAD

**Issue by pcborange** [Orange-OpenSource/angular-openlayers#2] opened 2016-05-04 13:50 UTC
Hello, 

Here after you can reproduce an error obtain when links number is greater than 10.

Thanks for your work on angular-openlayers and for your support ;-)

run "hello-from-nodejs-server.js"
access "http://127.0.0.1:1337/#/tenlinks"
Error here after occurs.
Refer to comment "AOL_BUG_TENLINKS" in "TenLinksController.js", comment corresponding line to have less then 10 links, error disappears.

Regards

[aol-bug.zip](https://github.com/Orange-OpenSource/angular-openlayers/files/248846/aol-bug.zip)

`angular.js:13550 TypeError: Cannot read property 'leaf' of undefined
    at Object.rbush._chooseSubtree (ol-debug.js:61302)
    at Object.rbush._insert (ol-debug.js:61339)
    at Object.rbush.insert (ol-debug.js:61148)
    at ol.structs.RBush.insert (ol-debug.js:61707)
    at ol.source.Vector.addFeatureInternal (ol-debug.js:62117)
    at ol.source.Vector.addFeature (ol-debug.js:62094)
    at aol.directives.Feature.onParentInstance (angular-openlayers.js:2539)
    at angular-openlayers.js:360
    at processQueue (angular.js:15961)
    at angular.js:15977(anonymous function) @ angular.js:13550$get @ angular.js:10225processQueue @ angular.js:15969(anonymous function) @ angular.js:15977$get.Scope.$eval @ angular.js:17229$get.Scope.$digest @ angular.js:17045$get.Scope.$apply @ angular.js:17337done @ angular.js:11572completeRequest @ angular.js:11778requestLoaded @ angular.js:11711
angular.js:13550 AssertionError: Assertion failed: uid (54) of value ([object Object]) does not exist
    at new goog.asserts.AssertionError (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4577:20)
    at Object.goog.asserts.doAssertFailure_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4634:11)
    at Object.goog.asserts.assert [as assert] (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4664:18)
    at ol.structs.RBush.update (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:61777:16)
    at ol.source.Vector.handleFeatureChange_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:62611:29)
    at ol.events.bindListener_.boundListener (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:5793:21)
    at ol.events.EventTarget.dispatchEvent (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:6500:24)
    at ol.Observable.changed (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:6615:8)
    at ol.Feature.handleGeometryChange_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:59411:8)
    at ol.events.bindListener_.boundListener (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:5793:21)(anonymous function) @ angular.js:13550$get @ angular.js:10225processQueue @ angular.js:15969(anonymous function) @ angular.js:15977$get.Scope.$eval @ angular.js:17229$get.Scope.$digest @ angular.js:17045$get.Scope.$apply @ angular.js:17337done @ angular.js:11572completeRequest @ angular.js:11778requestLoaded @ angular.js:11711
angular.js:13550 AssertionError: Assertion failed: uid (54) of value ([object Object]) does not exist
    at new goog.asserts.AssertionError (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4577:20)
    at Object.goog.asserts.doAssertFailure_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4634:11)
    at Object.goog.asserts.assert [as assert] (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4664:18)
    at ol.structs.RBush.update (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:61777:16)
    at ol.source.Vector.handleFeatureChange_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:62611:29)
    at ol.events.bindListener_.boundListener (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:5793:21)
    at ol.events.EventTarget.dispatchEvent (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:6500:24)
    at ol.Observable.changed (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:6615:8)
    at ol.Feature.handleGeometryChange_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:59411:8)
    at ol.events.bindListener_.boundListener (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:5793:21)(anonymous function) @ angular.js:13550$get @ angular.js:10225processQueue @ angular.js:15969(anonymous function) @ angular.js:15977$get.Scope.$eval @ angular.js:17229$get.Scope.$digest @ angular.js:17045(anonymous function) @ angular.js:17268completeOutstandingRequest @ angular.js:5869(anonymous function) @ angular.js:6145
angular.js:13550 AssertionError: Assertion failed: uid (54) of value ([object Object]) does not exist
    at new goog.asserts.AssertionError (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4577:20)
    at Object.goog.asserts.doAssertFailure_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4634:11)
    at Object.goog.asserts.assert [as assert] (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:4664:18)
    at ol.structs.RBush.update (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:61777:16)
    at ol.source.Vector.handleFeatureChange_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:62611:29)
    at ol.events.bindListener_.boundListener (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:5793:21)
    at ol.events.EventTarget.dispatchEvent (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:6500:24)
    at ol.Observable.changed (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:6615:8)
    at ol.Feature.handleGeometryChange_ (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:59411:8)
    at ol.events.bindListener_.boundListener (http://127.0.0.1:1337/bower_components/ol3/ol-debug.js:5793:21)`

**Comment by quentin-ol** [comment] 2016-05-10 16:35
Hey, a quick update on this issue, following assertions can be verified with this JSBin:  http://jsbin.com/xaziyakebi/1/edit?html,console,output .
- It seems that the bug occurs if and only if strictly more than 10 features are added to an empty `ol.source.Vector`. Adding more than 10 features to an already populated `ol.source.Vector` doesn't trigger the issue.
- The issue is related to the `RBush` struct used to store features in `ol.source.Vector`. Interestingly, the struct is initialized with a `maxEntries` parameters of 9.
- A work-around is to set the `useSpatialIndex` parameter of the `ol.source.Vector` to `false`. One can achieve that by passing `aol-use-spatial-index=false` to the `aol-source-vector` directive.

I'm not closing the issue until I reproduce the error without angular-openlayers.

**Comment by quentin-ol** [comment] 2016-05-13 09:36
Error reproduced without angular-openlayers: http://jsbin.com/litewuv/edit?html,js,console,output
Closing this issue and escalating to OpenLayers 3.

**Closed as completed by quentin-ol** 2016-05-13 09:36 UTC

**Comment by quentin-ol** [comment] 2016-05-13 16:19
Escalated to rbush: 
issue: https://github.com/mourner/rbush/issues/40 
PR: https://github.com/mourner/rbush/pull/41
